### PR TITLE
full refactor of packages.rs

### PR DESCRIPTION
**Pull request by WilliamAnimate**
totally O(n) time algorithm i promise

### CODE REVIEW

**Comment by XandrCopyrighted** [comment]
...

**Comment by XandrCopyrighted** [comment]
no more free commits <:[

**Comment by XandrCopyrighted** [comment]
I'll check it out later

**Comment by WilliamAnimate** [comment]
dont merge, im not ready

**Comment by WilliamAnimate** [comment]
> no more free commits <:[

no, this is open source, i contribute as i wish etc

**Comment by XandrCopyrighted** [comment]
> dont merge

wasn't going to, i'm at school and too busy to be checking on code.

**Comment by XandrCopyrighted** [comment]
I'm not saying that in a mean way btw

**Comment by WilliamAnimate** [comment]
actually yolo just merge it

this is only offically submitted to the AUR and arch linux defo works, and we can always fix it later:tm:

**Comment by XandrCopyrighted** [comment]
https://github.com/XandrCopyrighted/xFetch/actions/runs/7702894443/job/20992154875
haha

**Comment by XandrCopyrighted** [comment]
>:)

**Pull request merged**
