### PR TITLE
Add distro section

### PR DESCRIPTION
**Pull request by WilliamAnimate**

### CODE REVIEW

**Comment by WilliamAnimate** [comment]
oh damn it it has all of the other commits from #1
:facepalm: 
good luck fixing merge conflicts, should it become a problem

**Comment by XandrCopyrighted** [comment]
code approved, smh

**Comment by XandrCopyrighted** [comment]
OOPS

**Comment by XandrCopyrighted** [comment]
SORRY

**Comment by WilliamAnimate** [comment]
panic attack

**Pull request merged**
